import {Component,inject} from '@angular/core';
import {CommonModule} from '@angular/common';
import {ApiService,Dashboard,InvestmentHolding,WealthImportResult} from './api.service';
@Component({standalone:true,imports:[CommonModule],template:`<h2>Wealth dashboard</h2><p>Net worth</p><strong>{{d?.netWorth|number:'1.2-2'}}</strong><p>Cash {{d?.cash|number:'1.2-2'}} · Investments {{d?.investments|number:'1.2-2'}} · Assets {{d?.otherAssets|number:'1.2-2'}} · Liabilities {{d?.liabilities|number:'1.2-2'}}</p>`}) export class DashboardPage {private api=inject(ApiService);d?:Dashboard;constructor(){this.api.dashboard().subscribe(x=>this.d=x);}}
@Component({standalone:true,template:`<h2>Banking</h2><p>Accounts, transactions, categorization and reconciliation are available through the versioned API.</p>`}) export class BankingPage {}
@Component({standalone:true,template:`<h2>Expenses</h2><p>Expense categories, recurring rules, reporting and transaction linking are available through the application layer.</p>`}) export class ExpensesPage {}
@Component({standalone:true,imports:[CommonModule],template:`<h2>Investments</h2><p>Holdings are sourced from the deterministic investment ledger.</p><ul><li *ngFor="let h of holdings">{{h.securityId}} — {{h.quantity}} units — {{h.costBasis|number:'1.2-2'}}</li></ul>`}) export class InvestmentsPage {private api=inject(ApiService);holdings:InvestmentHolding[]=[];constructor(){this.api.holdings().subscribe(x=>this.holdings=x);}}
@Component({standalone:true,template:`<h2>Assets</h2><p>Physical and financial assets with valuation history.</p>`}) export class AssetsPage {}
@Component({standalone:true,template:`<h2>Liabilities</h2><p>Loans, repayments, interest and outstanding balances.</p>`}) export class LiabilitiesPage {}
@Component({standalone:true,imports:[CommonModule],template:`<h2>Imports</h2><p>Download one Excel-compatible CSV template, fill it in Excel, then upload it.</p><button (click)="downloadTemplate()">Download template</button><input type="file" accept=".csv" (change)="select($event)"><button [disabled]="!file||busy" (click)="upload()">{{busy?'Importing…':'Upload and import'}}</button><p>{{message}}</p><pre *ngIf="result">{{result|json}}</pre>`}) export class ImportsPage {private api=inject(ApiService);file?:File;busy=false;message='';result?:WealthImportResult;select(e:Event){const i=e.target as HTMLInputElement;this.file=i.files?.[0];this.message=this.file?`Selected ${this.file.name}`:'';}upload(){if(!this.file)return;this.busy=true;this.api.importWealth(this.file).subscribe({next:r=>{this.result=r;this.busy=false;this.message=r.success?`Imported ${r.rowsImported} records.`:'Import failed.';},error:e=>{this.busy=false;this.message=e?.error?.errors?.join(' ')||'Import failed.';}});}downloadTemplate(){const h='RecordType,ExternalId,Date,Institution,AccountNumber,AccountType,Currency,Description,Direction,Amount,Category,SecuritySymbol,SecurityName,SecurityType,Quantity,UnitPrice,Fees,AssetName,AssetType,AcquisitionValue,LiabilityName,LiabilityType,Principal,InterestRate,MaturityDate,PrincipalAmount,InterestAmount,ValuationValue';const b=new Blob([h+'\n'],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='PersonalWealth_Import_Template.csv';a.click();URL.revokeObjectURL(u);}}
