<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><RootNamespace>PersonalWealth.Api</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PersonalWealth.Application\PersonalWealth.Application.csproj" />
    <ProjectReference Include="..\PersonalWealth.Contracts\PersonalWealth.Contracts.csproj" />
    <ProjectReference Include="..\PersonalWealth.Infrastructure\PersonalWealth.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
</Project>
