using Microsoft.AspNetCore.Authentication.JwtBearer;
using PersonalWealth.Application.Tenancy;
using PersonalWealth.Application.Wealth;
using PersonalWealth.Infrastructure.Documents;
using PersonalWealth.Infrastructure.Persistence;
using PersonalWealth.Infrastructure.Tenancy;
using PersonalWealth.Infrastructure.Wealth;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpContextAccessor();
builder.Services.AddControllers();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => { options.Authority = builder.Configuration["Authentication:Authority"] ?? throw new InvalidOperationException("Authentication:Authority is required."); options.Audience = builder.Configuration["Authentication:Audience"] ?? throw new InvalidOperationException("Authentication:Audience is required."); });
builder.Services.AddAuthorization();
builder.Services.AddPersistence(builder.Configuration);
builder.Services.AddDocumentServices(builder.Configuration);
builder.Services.AddScoped<ITenantContext, HttpTenantContext>();
builder.Services.AddScoped<IWealthDashboardQuery, EfWealthDashboardQuery>();
var app = builder.Build();
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.Run();
public partial class Program;
