// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PersonalWealth.Infrastructure.Persistence;

#nullable disable

namespace PersonalWealth.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PersonalWealthDbContext))]
[Migration("20260910090000_EventReliability")]
partial class EventReliability
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("PersonalWealth.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("EventId").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<int>("AttemptCount").HasColumnType("int");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("EventType").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
            b.Property<string>("LastError").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
            b.Property<DateTimeOffset?>("NextAttemptAtUtc").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("OccurredAtUtc").HasColumnType("datetimeoffset");
            b.Property<string>("Payload").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<DateTimeOffset?>("PublishedAtUtc").HasColumnType("datetimeoffset");
            b.Property<byte[]>("RowVersion").IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
            b.Property<Guid?>("TenantId").HasColumnType("uniqueidentifier");
            b.HasKey("EventId");
            b.HasIndex("PublishedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc");
            b.HasIndex("TenantId", "PublishedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc");
            b.ToTable("OutboxMessages");
        });

        modelBuilder.Entity("PersonalWealth.Infrastructure.Persistence.ProcessedEvents.ProcessedEvent", b =>
        {
            b.Property<Guid>("EventId").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<string>("EventType").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
            b.Property<DateTimeOffset>("ProcessedAtUtc").HasColumnType("datetimeoffset");
            b.HasKey("EventId");
            b.ToTable("ProcessedEvents");
        });
#pragma warning restore 612, 618
    }
}
