using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace PersonalWealth.Infrastructure.Persistence.Migrations;
public partial class AssetsLiabilities : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.CreateTable("Assets", t => new { Id=t.Column<Guid>("uniqueidentifier",false), TenantId=t.Column<Guid>("uniqueidentifier",false), Name=t.Column<string>("nvarchar(200)",maxLength:200,false), Type=t.Column<string>("nvarchar(30)",maxLength:30,false), Currency=t.Column<string>("nvarchar(3)",maxLength:3,false), AcquisitionValue=t.Column<decimal>("decimal(19,4)",false), AcquisitionDate=t.Column<DateTime>("datetime2",false), IsActive=t.Column<bool>("bit",false), CreatedAt=t.Column<DateTime>("datetime2",false), UpdatedAt=t.Column<DateTime>("datetime2",true), }, c=>c.PrimaryKey("PK_Assets",x=>x.Id));
        m.CreateTable("Liabilities", t => new { Id=t.Column<Guid>("uniqueidentifier",false), TenantId=t.Column<Guid>("uniqueidentifier",false), Name=t.Column<string>("nvarchar(200)",maxLength:200,false), Type=t.Column<string>("nvarchar(30)",maxLength:30,false), Currency=t.Column<string>("nvarchar(3)",maxLength:3,false), OriginalPrincipal=t.Column<decimal>("decimal(19,4)",false), OutstandingPrincipal=t.Column<decimal>("decimal(19,4)",false), AnnualInterestRate=t.Column<decimal>("decimal(9,4)",false), StartDate=t.Column<DateTime>("datetime2",false), MaturityDate=t.Column<DateTime>("datetime2",true), IsActive=t.Column<bool>("bit",false), CreatedAt=t.Column<DateTime>("datetime2",false), UpdatedAt=t.Column<DateTime>("datetime2",true) }, c=>c.PrimaryKey("PK_Liabilities",x=>x.Id));
        m.CreateTable("AssetValuations", t=>new { Id=t.Column<Guid>("uniqueidentifier",false), TenantId=t.Column<Guid>("uniqueidentifier",false), AssetId=t.Column<Guid>("uniqueidentifier",false), ValuationDate=t.Column<DateTime>("datetime2",false), Value=t.Column<decimal>("decimal(19,4)",false), Source=t.Column<string>("nvarchar(100)",maxLength:100,false), CreatedAt=t.Column<DateTime>("datetime2",false), UpdatedAt=t.Column<DateTime>("datetime2",true) }, c=>{c.PrimaryKey("PK_AssetValuations",x=>x.Id);c.ForeignKey("FK_AssetValuations_Assets_AssetId",x=>x.AssetId,"Assets","Id",onDelete:ReferentialAction.Cascade);});
        m.CreateTable("LiabilityRepayments", t=>new { Id=t.Column<Guid>("uniqueidentifier",false), TenantId=t.Column<Guid>("uniqueidentifier",false), LiabilityId=t.Column<Guid>("uniqueidentifier",false), PaymentDate=t.Column<DateTime>("datetime2",false), Amount=t.Column<decimal>("decimal(19,4)",false), PrincipalAmount=t.Column<decimal>("decimal(19,4)",false), InterestAmount=t.Column<decimal>("decimal(19,4)",false), CreatedAt=t.Column<DateTime>("datetime2",false), UpdatedAt=t.Column<DateTime>("datetime2",true) }, c=>{c.PrimaryKey("PK_LiabilityRepayments",x=>x.Id);c.ForeignKey("FK_LiabilityRepayments_Liabilities_LiabilityId",x=>x.LiabilityId,"Liabilities","Id",onDelete:ReferentialAction.Cascade);});
        m.CreateIndex("IX_Assets_TenantId_Name","Assets",new[]{"TenantId","Name"}); m.CreateIndex("IX_Liabilities_TenantId_Name","Liabilities",new[]{"TenantId","Name"}); m.CreateIndex("IX_AssetValuations_TenantId_AssetId_ValuationDate","AssetValuations",new[]{"TenantId","AssetId","ValuationDate"}); m.CreateIndex("IX_LiabilityRepayments_TenantId_LiabilityId_PaymentDate","LiabilityRepayments",new[]{"TenantId","LiabilityId","PaymentDate"});
    }
    protected override void Down(MigrationBuilder m) { m.DropTable("LiabilityRepayments");m.DropTable("AssetValuations");m.DropTable("Liabilities");m.DropTable("Assets"); }
}
